export type Fase =
  | "INICIO_TURNO"
  | "ACCION_JUGADOR"
  | "PRERESOLUCION_OBJETIVOS" //MOVER HACIA ADELANTE Y GENERAR OTRO EVENTO CON OBJETIVO, O ESQUIVAR HACIA ATRAS
  | "RESOLUCION_OBJETIVOS"
  | "FIN_TURNO";
